import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '../styles/app.scss';
import Header from '@/components/Header';
import 'antd/dist/reset.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className + ' relative'}>
        <Header />
        <div className='mt-[-18px]' style={{ height: 'calc(100vh - 66px)' }}>
          {children}
        </div>
      </body>
    </html>
  );
}
