/* eslint-disable @next/next/no-page-custom-font */
import { RootStyleRegistry } from '@/app/RootStyleRegistry';
import Header from '@/components/Header';
import 'antd/dist/reset.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../styles/app.scss';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link
          href='https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@0,300..800;1,300..800&display=swap'
          rel='stylesheet'
        />
      </head>
      <RootStyleRegistry>
        <body className={inter.className + ' relative'}>
          <Header />
          <div className='mt-[42px]' style={{ height: 'calc(100vh - 66px)' }}>
            {children}
          </div>
        </body>
      </RootStyleRegistry>
    </html>
  );
}
